### ISSUE TITLE
Upstream conda-lock changes are non-compatible with the IronBank workflow's update_ib_files.py

### ISSUE THREAD

**Issue by rigzba21** [MetroStar/conda-vendor#33]
When running the [IronBank `update_ib_files.py`](https://repo1.dso.mil/dsop/opensource/metrostar/miniconda/-/blob/development/scripts/update_ib_files.py) the following error shows up:
```python
Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/update_ib_env/bin/conda-vendor", line 6, in <module>
    from conda_vendor.__main__ import cli
  File "/usr/local/Caskroom/mambaforge/base/envs/update_ib_env/lib/python3.9/site-packages/conda_vendor/__main__.py", line 4, in <module>
    from conda_vendor.cli import (
  File "/usr/local/Caskroom/mambaforge/base/envs/update_ib_env/lib/python3.9/site-packages/conda_vendor/cli.py", line 3, in <module>
    from conda_vendor.conda_channel import CondaChannel
  File "/usr/local/Caskroom/mambaforge/base/envs/update_ib_env/lib/python3.9/site-packages/conda_vendor/conda_channel.py", line 11, in <module>
    from conda_lock.conda_lock import solve_specs_for_arch
ImportError: cannot import name 'solve_specs_for_arch' from 'conda_lock.conda_lock' (/usr/local/Caskroom/mambaforge/base/envs/update_ib_env/lib/python3.9/site-packages/conda_lock/conda_lock.py)
```

Looks like this is due to some changes in [upstream conda-lock's src_parser module](https://github.com/conda-incubator/conda-lock/blob/388db9f0b20a2f440ced73bb24afe6995506c784/conda_lock/src_parser/__init__.py#L43) that introduce dependencies as a ```List(VersionedDependencies)``` which breaks the current version of conda-vendor

~~WIP PR: https://github.com/MetroStar/conda-vendor/pull/32~~

**Comment by rigzba21** [comment]
Please see https://github.com/MetroStar/conda-vendor/issues/34

**Comment by jbouder** [comment]
Closing stale issue.
